class Poule {

    constructor(id,nom, date_arrivee, couleur, statut,date_naissance, alimentation,race) {
        this.id = id;  // id of the egg (auto-generated by the database)  // id of the poule (auto-generated by the database)  // id of the poule (auto-generated by the database)  // id of the poule (auto-generated by the database)  // id of the poule (auto-generated by the database)  // id of the poule (auto-generated by the database)  // id of the
        this.nom = nom;
        this.date_arrivee = date_arrivee
        this.couleur = couleur
        this.statut_sante = statut
        this.date_naissance = date_naissance
        this.alimentation = alimentation
        this.race = race
    }
}

module.exports = Poule